version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    allow:
      - dependency-type: direct
    commit-message:
      prefix: "chore(deps)"
